### ISSUE TITLE
Not getting proper output for speech to text translation in dynamoDB

### ISSUE THREAD

**Issue by madmaxgorgon** [amazon-connect/amazon-connect-realtime-transcription#24]
Hello I am trying to get the transcription from customer call. I was able to get the audio in S3 bucket. But at the time of real time transcription I am not getting exact output.
Ex. When I say "balance" or anything else it is just storing Recorded,Courted or where did.
It is not storing the actual speech.

**Comment by madmaxgorgon** [comment]
Hello,
Can anyone give me quick update on this?

**Comment by efh365** [comment]
Hi, sorry for the delay here. Are you saying that everything you speak is being stored as one word or that the word 'balance' is not being understood properly? 

Audio over KVS is streamed at 8kHz due to telephony restrictions so the transcription may not be 100% accurate. You can help make transcription more accurate by adding custom vocabulary and bu turning off the feature to block background noise on your phone.
