### ISSUE TITLE
UnknownHostException: transcribestreaming.ap-northeast-1.amazonaws.com

### ISSUE THREAD

**Issue by jinspark-lab** [amazon-connect/amazon-connect-realtime-transcription#46]
Hi, I am trying to test this sample for making customer demo.

In the Lambda function "kvsTranscriber" which is implemented as Java returns error as belows.
There are several errors when this function is triggered. Of course there is no record files on S3

TranscribeStreamingRetryClient:164 - Error occurred on channel AUDIO_FROM_CUSTOMER : software.amazon.awssdk.core.exception.SdkClientException

Caused by: software.amazon.awssdk.core.exception.SdkClientException
Caused by: java.net.UnknownHostException: transcribestreaming.ap-northeast-1.amazonaws.com

Could you give me a solution?
I just ran CloudFormation Stacks from the document.

**Comment by efh365** [comment]
The transcribe service we are using in this solution is Transcribe Streaming, not just Transcribe. Currently Transcribe Streaming is not available in ap-northeast-1, which is why it is not working. You can see the available regions here: https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ (Transcribe Streaming is marked after the table in italics)
