### ISSUE TITLE
error - connectaudioutils

### ISSUE THREAD

**Issue by angel7170** [amazon-connect/amazon-connect-realtime-transcription#61]
Cloud formation stack is failing at this step

Please let me know as to what I am doing wrong
![error-connectaudioutils](https://user-images.githubusercontent.com/58609234/127029782-46ec9e08-e640-4bc3-be53-d1793b66da0f.png)

**Comment by mcosicaws** [comment]
I believe this error is caused by `layer.zip` file not being present in the S3 deployment bucket. 
Could you please check if this file exists in the S3 deployment bucket?

This section: https://github.com/amazon-connect/amazon-connect-realtime-transcription#easy-setup
describes the steps:

- Clone the GitHub repo to a local folder on your computer
- Create an S3 bucket and create a new folder in the bucket: `deployment`
- Upload the `deployment/` folder from the solution (you cloned) into `deployment` folder in the created bucket

Could you please test, and let us know the result?

Thanks,
Milos

**Comment by mcosicaws** [comment]
Closing due to no response, please feel free to re-open should you need any additional help.
